server:
  port: 18080
  
spring:
  application:
    name: file
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    hikari:
      connection-test-query: SELECT NOW() FROM dual
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/file?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: file
      password: qwe123!@#
    
logging:
  config: classpath:logback-spring.xml

eureka:
  instance:
    hostname: ${spring.application.name}
    secure-virtual-host-name: ${spring.application.name}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
    register-with-eureka: true
    fetch-registry: false