server:
  port: 18080
  error:
    include-exception: true
    include-stacktrace: always
spring:
  application:
    name: zuul
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: D:/Temp
      max-file-size: 100MB
      max-request-size: 500MB

zuul:
  ignored-services: "*"
  routes:
    auth:
      path: /auth/**
      url: http://127.0.0.1:38080/
      strip-prefix: false
    notification:
      path: /notification/**
      url: http://127.0.0.1:28080/
      strip-prefix: false
    
management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: false
 
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
    register-with-eureka: true
    fetch-registry: false
