server:
  port: 18080
  error:
    include-exception: true
    include-stacktrace: always
spring:
  application:
    name: zuul
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: D:/Temp
      max-file-size: 100MB
      max-request-size: 500MB

zuul:
  ignored-services: "*"
  routes:
    auth:
      path: /auth/**
      url: http://127.0.0.1:38080/
      strip-prefix: false
    notification:
      path: /notification/**
      url: http://127.0.0.1:28080/
      strip-prefix: false
    file:
      path: /file/**
      url: http://127.0.0.1:18080/
      strip-prefix: false
    
management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: false
 
eureka:
  instance:
    hostname: ${spring.application.name}
    secure-virtual-host-name: ${spring.application.name}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
    register-with-eureka: true
    fetch-registry: false
