server:
  port: 8081
  error:
    include-exception: true
    include-stacktrace: always
  
spring:
  application:
    name: zuul
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: /Temp
      max-file-size: 100MB
      max-request-size: 500MB
      
zuul:
  host:
    connect-timeout-millis: 5000
    connection-request-timeout-millis: 5000
    socket-timeout-millis: 5000
  ignored-services: "*"
  routes:
    auth:
      path: /auth/**
      url: http://127.0.0.1:38080/
      strip-prefix: false
    notification:
      path: /notification/**
      url: http://127.0.0.1:28080/
      sensitive-headers:
      - authorization, set-cookie
      strip-prefix: false
    file:
      path: /file/**
      url: http://127.0.0.1:18080/
      strip-prefix: false
    
management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: false
 
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
    register-with-eureka: true
    fetch-registry: false
