server:
  port: 8081
  
spring:
  application:
    name: zuul
  servlet:
    multipart:
      file-size-threshold: 100MB
      location: /Temp
      max-file-size: 100MB
      max-request-size: 500MB
      
zuul:
  host:
    connect-timeout-millis: 5000
    connection-request-timeout-millis: 5000
    socket-timeout-millis: 5000
  ignored-services: "*"
  routes:
    auth:
      path: /auth/**
      strip-prefix: false
    notification:
      path: /notification/**
      sensitive-headers:
      - authorization, set-cookie
      strip-prefix: false
    file:
      path: /file/**
      strip-prefix: false
 
ribbon:  eureka:    enabled: true
    
auth:
  ribbon:
    listOfServers: http://127.0.0.1:38080/
    
notification:
  ribbon:
    listOfServers: http://127.0.0.1:28080/
 
file:
  ribbon:
    listOfServers: http://127.0.0.1:18080/
 
eureka:
  instance:
    instance-id: ${spring.application.name} 
    virtual-host-name: ${spring.application.name}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
    register-with-eureka: true
    fetch-registry: true
