server:
  port: 8080
  error:    include-exception: true
    include-stacktrace: always
  
spring:  application:    name: eureka
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  
eureka:
  instance:
    hostname: 127.0.0.1
  server:
    eviction-interval-timer-in-ms: 1000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false